sentry:
  dsn: # Intentionally left empty for development

spring:
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          discord:
            authorization-grant-type: authorization_code
            client-id: # Intentionally left empty for development
            client-secret: # Intentionally left empty for security
            redirect-uri: http://localhost:8080/login/oauth2/code/discord
            scope:
              - identify
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
