CREATE TABLE IF NOT EXISTS scorecard (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	deleted BOOLEAN,
	id_member INTEGER,
	id_coach INTEGER,
	id_score_group INTEGER,
	id_score_personal INTEGER,
	uuid TEXT,
	date TEXT,
	time TEXT,
	workout_intensity INTEGER,
	mighterium_collected INTEGER,
	exercises TEXT,
	image_title TEXT,
	image_bytes BLOB,
	FOREIGN KEY (id_member) REFERENCES member (id),
	FOREIGN KEY (id_coach) REFERENCES coach (id),
	FOREIGN KEY (id_score_group) REFERENCES score (id),
	FOREIGN KEY (id_score_personal) REFERENCES score (id)
);
